org.gradle.jvmargs=-Xmx4G
org.gradle.workers.max=5
org.gradle.daemon=true
org.gradle.parallel=true



mod_id=enlighten

mod_name=Enlighten
mod_license=MIT License
mod_version=0.0.1
mod_group_id=me.clefal.examplemod
mod_authors=Clefal
mod_description=
mod_issue=https://github.com/TUsama/Whats-Your-Build/issues
deps.fabric_loader=0.16.10
deps.fzzy_config_version = 0.7.0
deps.lib_version=2.0.17
deps.common_networking=1.0.22

